edits from AD review
danielfett/draft-dpop pull request #173
Opened 2022-11-14 23:15 UTC by b---c

edits addressing AD review https://mailarchive.ietf.org/arch/msg/oauth/gd9k8wF2h9mBCoqORaD83vbRFl0/

2022-11-29 07:40 UTC, danielfett requested changes
Thanks for updating the draft! I have some minor comments, but overall this looks good to me.

2022-11-29 07:40 UTC, danielfett commented on main.md
> + * `alg`: a JWS algorithm identifier, from the registered algorithms [@IANA.JOSE.ALGS], of an asymmetric digital signature.
Maybe like this?
```suggestion
 * `alg`: an identifier for a JWS asymmetric digital signature algorithm from [@IANA.JOSE.ALGS].
```

2022-11-29 07:40 UTC, danielfett commented on main.md
> +is no additional risk of token replay.
I'm not sure if 'tracked' is enough here?

2022-11-29 07:40 UTC, danielfett commented on main.md
> +specific endpoints to use arbitrarily far into the future by choosing the
There's some ambiguity here which we can avoid by removing the "to use" part.
```suggestion
specific endpoints arbitrarily far into the future by choosing the
```

2022-11-29 07:40 UTC, danielfett commented on main.md
> +Servers accepting signed DPoP proof JWTs MUST check the `typ` field is `dpop+jwt` in the
```suggestion
Servers accepting signed DPoP proof JWTs MUST verify that the `typ` field is `dpop+jwt` in the
```

2022-11-29 15:07 UTC, b---c commented on main.md
> + * `alg`: a JWS algorithm identifier, from the registered algorithms [@IANA.JOSE.ALGS], of an asymmetric digital signature.
wfm

2022-11-29 15:17 UTC, danielfett commented on main.md
> +is no additional risk of token replay.
Sounds good!

2022-11-29 15:49 UTC, b---c commented
>

2022-11-29 15:51 UTC, b---c commented
Thanks for the minor comments/suggestions. I believe all have been incorporated.

2022-11-30 08:31 UTC, danielfett approved these changes

2022-11-30 12:32 UTC, merged